<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/10/31
 * Time: 11:05
 */
namespace backend\models;

use yii\db\ActiveRecord;

class Cooperation extends ActiveRecord{

    public function rules()
    {
//        return parent::rules(); // TODO: Change the autogenerated stub
        return [
            [['period','price'],'required'],
            [['period',], 'integer', 'message' => '必须为整数'],
            [['price'],'number','message' => '请输入数字']
        ];
    }

    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'comment' => '文字介绍',
            'price' => '价格',
            'period'=>'周期',
        ];
    }

    public static function initModel($id = null)
    {
        if (!empty($id)) {
            return self::findOne($id);
        }
        $model = new self();
        $model->loadDefaultValues();
        return $model;
    }
}